# Generated by Django 4.2.3 on 2023-08-10 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('average_image_processing_time', models.DecimalField(decimal_places=10, max_digits=20)),
                ('average_image_size', models.IntegerField()),
                ('average_image_labels_count', models.IntegerField()),
                ('last_logged_users_count', models.IntegerField()),
                ('last_joined_users_count', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
